# Generated by Django 5.0.6 on 2024-07-02 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_category_slug_product_slug'),
        ('shop', 'slug'),
    ]

    operations = [
    ]
